### ISSUE TITLE
Latest version of VRCFT doesn't work with the OSC mod.

### ISSUE THREAD

**Issue by ModernBalloonie** [kafeijao/Kafe_CVR_Mods#47]
Hello! I'm trying to use the latest version of VRCFaceTracking in CVR, However, there's an issue. The avatar status says "Loading", and it seems like VRCFaceTracking isn't getting the configs.

https://github.com/benaclejames/VRCFaceTracking/releases/tag/5.2.3.0

Here's the latest version that i'm trying to use. Thank you!

**Comment by Pyrarrows** [comment]
Having the same issue as well with the same version of VRCFaceTracking, looks like the OSC mod isn't communicating with that version of VRCFaceTracking at all.

**Comment by kafeijao** [comment]
I'm not sure when I'm going to have time to tackle this. It makes it specially hard since I don't have face or eye tracking.

There seems to be a solution provided by dragonskyrunner and tikkaqrow in the [CVRMG discord](https://discord.gg/dndGPM3bxu) on [this message](https://discord.com/channels/1001388809184870441/1001388935819309126/1233857448729907250)

> need to use an older version of VRCFT
5.1.1.0 is the newest you can use on CVR, also you need Kafei's OSC mod, with VRCFT compatibility toggled on. Download the .msix file. Don't intall it tho. It's MS security certs are out of date, instead extract the .msix with 7-zip, stick the extracted files wherever you want, and directly run the VRCFT .exe binary within.
> https://github.com/benaclejames/VRCFaceTracking/releases/tag/5.1.1.0

**Comment by Pyrarrows** [comment]
Ok, will give that a try again, did try it yesterday, but found that the older versions wouldn't install because the certificate that they're signed with expired on April 11.  I just got the older version to install, had to change my system clock back to April 10 2024, will try it out again later in the day.

**Comment by kafeijao** [comment]
There is a new mod that should handle this functionality: https://github.com/200Tigersbloxed/VRCFT2CVR
